---
# Se descargan los paquetes
- name: Download of asterisk sources
  git: repo={{ asterisk_repo }} dest=/usr/src/asterisk version={{ asterisk_version }}
  tags: ['changeversion']

# Pasos para instalar asterisk  se comienza con el install de prerequisitos y luego con el configure
- name: CentOS Installation of prerequisites packages
  shell: "{{ item }} chdir=/usr/src/asterisk/"
  with_items:
    - contrib/scripts/install_prereq install
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0
  when: ansible_os_family == "RedHat"

# Esta task es necesaria porque en debian hay un paquete que pregunta cual es el countrycode telefonico del pais donde va a estar asterisk instalado
# El debconf sirve para confirugarle predeterminadamente la opcion de 59 (country code argentino) y asi no pida el input
- name: Ubuntu/Debian Set country code for libvp0 package
  debconf: name='libvpb0' question='libvpb1/countrycode' value={{ country_code }} vtype='string'
  when: ansible_os_family == "Debian"

# Toca pasarle el echo 'y' a este script porque pide confirmacion de paquetes en debian
- name: Ubuntu/Debian Installation of prerequisites packages (debian)
  shell: "echo 'y' | contrib/scripts/install_prereq install chdir=/usr/src/asterisk"
  when: ansible_os_family == "Debian"
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0

- name: Download of res_json module
  git: repo={{ res_json_repo }} dest=/usr/src/asterisk/asterisk-res_json/ version=master
  tags: ['changeversion']

- name: Execute res_json install script
  shell: "./asterisk-res_json/install.sh chdir=/usr/src/asterisk"
  tags: ['changeversion']

# Se sigue con el la ejecucion del configure, esto para el PE
- name: Configure of asterisk
  shell: "./configure --libdir={{ install_prefix }}/asterisk/lib64 --prefix={{ install_prefix }}/asterisk --with-jansson-bundled chdir=/usr/src/asterisk"
  tags: ['changeversion']

# Se ejecuta la instalacion de asterisk
- name: CentOS Make menuselect opts and make install of Asterisk
  shell: "{{ item }} chdir=/usr/src/asterisk"
  with_items:
    - make menuselect.makeopts
    - menuselect/menuselect --disable BUILD_NATIVE menuselect.makeopts
    - menuselect/menuselect --enable res_json menuselect.makeopts
    - menuselect/menuselect --enable codec_opus menuselect.makeopts
    - make -j 10
    - make install
    - make samples
    - make config
    - ldconfig
  retries: 6
  delay: 3
  register: result
  until: result.rc == 0
  when: ansible_os_family == "RedHat"
  tags: ['changeversion']

- name: Ubuntu/Debian Make menuselect opts and make install of Asterisk
  shell: "{{ item }} chdir=/usr/src/asterisk"
  with_items:
    - make menuselect.makeopts
    - menuselect/menuselect --disable BUILD_NATIVE menuselect.makeopts
    - menuselect/menuselect --enable res_json menuselect.makeopts
    - menuselect/menuselect --enable codec_opus menuselect.makeopts
    - make -j 10
    - make install
    - make samples
    - make config
    - ldconfig
  retries: 6
  delay: 3
  when: ansible_os_family == "Debian"
  tags: ['changeversion']

# Se borran los paquetes descargados
- name: Erase the downloaded directories of asterisk
  file: path=/usr/src/asterisk state=absent
  tags: ['changeversion']
